### PR TITLE
Add virtual keyword to implemented virtual functions

### PR DESCRIPTION
**Pull request by cmastalli**
This PR solves the issue #278.

### CODE REVIEW

**Comment by wxmerkt** [comment]
Awesome, thank you for fixing this important issue. Since we implicitly have a C++11 requirement (URDF parser, also see CI requiring C++11 on Xenial), we may want to use `override` when overriden to indicate it's not the first declaration

**Comment by cmastalli** [comment]
> Awesome, thank you for fixing this important issue. Since we implicitly have a C++11 requirement (URDF parser, also see CI requiring C++11 on Xenial), we may want to use `override` when overriden to indicate it's not the first declaration

It sounds good for me.
Maybe we need to discuss when it coudl happen.
@nim65s could you let us know if we can pursue c++11 standard soon? or when?

**Comment by nim65s** [comment]
I think for crocoddyl, we can decide to require c++11. And for almost all other softwares, but not on the very generic ones like eigenpy, hpp-fcl & pinocchio.

**Comment by jcarpent** [comment]
I don't think that you need to use any C++11 feature here. robotpkg is forcing C++11, but this is a mistake and it will be fixed soon. 
And Xenial still relies on urdf 0.4.2 which is using boost::shared_ptr

**Comment by wxmerkt** [comment]
Is there a requirement to still support C++ < C++14? Even on Xenial the default compilers support the features.

**Comment by jcarpent** [comment]
We would prefer to not impose any restriction if it is not required. In the current context, adding or not "override" won't change anything, except adding C++11 as required feature, while until now, the code is compatible with all the standards, meaning that extra-lib can still use it.

**Comment by jcarpent** [comment]
In addition, for C++14, not all the compilers are enforcing correctly all the rules, making hard to use this feature on all the platforms even if they claim it.

**Pull request merged**
