### PR TITLE
Register converters for shared_ptrs of solver classes

### PR DESCRIPTION
**Pull request by cmastalli**
This PR should solve the request in #859.

@edantec could you test it from your side?

### CODE REVIEW

**Comment by cmastalli** [comment]
I will merge this PR, but it would be still useful if this fixes your issue @edantec.

**Comment by edantec** [comment]
I'll test it as soon as possible, thank you

**Comment by edantec** [comment]
It solves my problem and I can now use FDDP with python bindings, thank!

**Comment by cmastalli** [comment]
> It solves my problem and I can now use FDDP with python bindings, thank!

Happy for that :)

**Pull request merged**
