### PR TITLE
crocoddyl logo

### PR DESCRIPTION
**Pull request by proyan**

### CODE REVIEW

**Comment by jcarpent** [comment]
I would remove the next figure, the one below the logo. It is too much.

**Comment by cmastalli** [comment]
> I would remove the next figure, the one below the logo. It is too much.

@jcarpent  I like that figure. It gives a good impression IMHO.

**Review by cmastalli — APPROVED** [review]
I am happy with the changes.
I don't think we need to modify other parts of the readme file.
Probably, I would add the figure in the doxygen documentation (cover page). However this could be done later.

**Comment by jcarpent** [comment]
The figure should appear later in the page now the logo is present. I suggest that for readability and clarity.

**Comment by cmastalli** [comment]
> The figure should appear later in the page now the logo is present. I suggest that for readability and clarity.

Ok, this sounds good for me as well. But I would say "still close to the introduction".

**Comment by proyan** [comment]
I've moved the image to Crocoddyl features.

**Review by jcarpent — APPROVED** [review]
Much better I think. Thanks a lot for considering this change.

**Pull request merged**
