### PR TITLE
Simple urdf example

### PR DESCRIPTION
**Pull request by justinberi**
**Description**

There was no simplified example using an urdf and activation model and I thought this might be useful to others who are also starting out.

All the existing examples (from example-robots-data) require meshes which are annoying for prototyping simple configurations. 

If you wish I can also do up a cartpole example.

### CODE REVIEW

**Comment by hrp2-14** [comment]
Hi ! This project doesn't usually accept pull requests on master. If this wasn't intentionnal, you
can change the base branch of this pull request to devel (No need to close it for that). Best, a bot.

**Review by cmastalli — CHANGES_REQUESTED** [review]
Hi @justinberi 

Thank you for being a proactive member of our community.
We are keen to have many contributors like you.

However, for this particular case, I need to unfortunately reject the PR in its form.
We would like to avoid having URDF (or robot related) code in our repository.
We developed `example-robot-data` for such purpose.

Said that, I believe your PR goal is fair.
If you wish to pursue it, then I suggest to take the following action points:
 1. Substitute the URDF for a Pinocchio code that creates this model.
 - This shouldn't be difficult if you know enough Pinocchio.
 2. Create a Jupyter notebook, instead of a Python script
 - This will be nicer as you go step-by-step in the creation of the robot and actuation models

Let me know if you wish to do it. Otherwise, I will close this PR as I don't have bandwidth to resolve these action points.

Again, thanks for being proactive!

**Comment by nim65s** [comment]
Hi @justinberi,
I agree that it would be nice to have a simple robot model with basic geometries instead of meshes (in example-robot-data, only `simple_humanoid_description` doesn't have meshes, but it doesn't have visual at all…). 

But as @cmastalli noted, we usually share our robot models among our different projects in that example-robot-data package. Therefore, I guess you could open a PR with this urdf there. Would this work for you ?

**Comment by wxmerkt** [comment]
We can always use `pinocchio.buildSampleModelManipulator` and `pinocchio.buildSampleGeometryModelHumanoid` or manual creation as pointed out by Carlos to have examples that won't require example-robot-data

**Comment by justinberi** [comment]
Hi all,

Thank you for the feedback. All seems logical and I'd like to pursue the idea. The goal of the PR was to create an urdf and example script that others could use to easily different robot configurations. So I will do the following:

1. Close this PR.
2. Create a PR (or issue?) in example-robot-data and move `double_pendulum_simple.urdf` to that repo.
3. Create a PR (or issue?) in crocoddyl for and convert `simple_urdf.py` to a notebook.

@cmastalli I may create a separate issue to demonstrate pinocchio for creating the model in the future but I will limit the scope of this work for moment

Does that seem fair?

**Comment by cmastalli** [comment]
> Does that seem fair?

Yes, it does.
Note that we need to wait for a new release (in example-robot-data) before merging the notebook in Crocoddyl.

**Pull request closed without merging**
