### PR TITLE
Updates for MEMMO deliverable: install utils, add createCoMGoalProblem, allow update of references

### PR DESCRIPTION
**Pull request by wxmerkt**
- Adds `createCoMGoalProblem` as used in the MEMMO D3.3 deliverable
- Turns const-pointer return values into non-const to allow update of xref/Mref (reduces overhead in MPC)
- Install utils

### CODE REVIEW

**Comment by wxmerkt** [comment]
Good to merge?

**Comment by wxmerkt** [comment]
Done, let's make sure we get this merged today for the deliverable

**Comment by cmastalli** [comment]
@wxmerkt thanks for the nice job :smiley:

**Comment by wxmerkt** [comment]
Thank you for the swift action :-)

**Pull request merged**
