### PR TITLE
Fixed GV display after changes in #911

### PR DESCRIPTION
**Pull request by cmastalli**
Note that this error was not triggered by running the examples with `display` option.

### CODE REVIEW

**Comment by cmastalli** [comment]
I have pushed a commit that includes another feature!
Now, the Python users can also define the type of dependency in the residual function.

**Review by jcarpent — COMMENTED** [review]
I would say that these properties should not change after construction.

**Comment by cmastalli** [comment]
> I would say that these properties should not change after construction.

Yes, I agree with you. I will change this bit asap.

**Comment by proyan** [comment]
@cmastalli This PR should be okay to merge once you could take care of Justin's concerns

**Comment by cmastalli** [comment]
This is the list of changes:
 1. I have included the definition of the dependencies in the constructor API (the only way to avoid that users modify it).
 2. I have also used this API for constructing all the residuals (important for resolving nondeterminism when nu is equals to 0)
 3. I have defined the q,v,u_dependent flags for the control residual (this bit was missed in previous PR).
 4. I have fixed a tiny issue in the computation of u_dependent terms in the CostModelResidual class.

**Comment by cmastalli** [comment]
@proyan and @jcarpent -- let me know if you are happy with the provided solution. Otherwise, I will merge this PR tomorrow afternoon.

**Review by proyan — APPROVED** [review]
Thanks Carlos for this fix

**Pull request merged**
