### PR TITLE
Cleaned up and fixed minor issues in the documentiobn of cost related classes

### PR DESCRIPTION
**Pull request by cmastalli**
This PR basically cleans up a bit the code:
  - fixed minor things in the documentation
  - used throw_pretty in the Python bindings of cost-base (as done in other cases)
  - simplified a bit more the code (nothing dramatic)

### CODE REVIEW

**Comment by cmastalli** [comment]
@proyan I will merge this PR since it is basically a maintained task. No need to be reviewed IMHO.

**Comment by proyan** [comment]
This PR was proposed at 11:23h, and was merged at 13:06h.

I would prefer if you wait for a review before merging a PR.

**Comment by cmastalli** [comment]
>  I would prefer if you wait for a review before merging a PR.

Ok, I will do it next time.
Concretely speaking, I will wait for at least 8 hrs if someone wants to be a reviewer.
Is this OK for you?

(Of course, for critical PRs, I will wait more time.)

**Comment by nim65s** [comment]
We already discussed this: please also consider working hours. A PR opened at 11pm on Saturday can't be merged without reviews at 7am on Sunday.

**Comment by proyan** [comment]
I think we have a good policy of _requiring_ a PR to be reviewed before it is merged. I would prefer if you followed this policy for all PRs. Making an arbitrary distinction between "critical" and "non-critical" PRs would not be good practice.

**Pull request merged**
