### PR TITLE
Release v2.0.0

### PR DESCRIPTION
**Pull request by cmastalli**
In this release, we have achieved several improvements:
 - Changed stopping criteria to better evaluate the converge criteria
 - Extended numdiff routines to compute second-order derivatives + other minor improvements
 - Improved the overall project documentation (still many things to be done)
 - Added collision residual unit tests and missing Python bindings
 - Allowed accuracy configuration of verbose callback
 - Closed gaps once feasibility is achieved in FDDP
 - Supported different Python versions
 - Added procedure to check example log files
 - Added support to M1 apple chip + fixed compilation issues with Clang
 - Fixed a small issue in the solver's Armijo condition
 - Added `shareMemory` unit tests
 - Introduced the notion of resizing data in solvers
 - Added unit test for impulse actions
 - Deprecated `set_id` functions in contact residuals
 - Supported Ipopt solver with Python bindings
 - Extended (diff)-action API to handle arbitrary constraints + unit tests
 - Introduce the notion of `ConstraintManager` and used it in diff-actions + unit tests + integrated action support
 - Added the HyQ robot for extra unit testing
 - Updated doxygen documentation in many parts of the project
 - Used std::set for storing cost/constraint activation status
 - Fixed small issues in terminal-node computations
 - Supported Meshcat display of contact forces, friction cone and foot-swing trajectories
 - Introduced the notion of equality constraint feasibility in solvers
 - Created a data collector to store joint effort and accelerations
 - Created joint-effort/acceleration residuals + unit tests
 - Created inverse-dynamics action models + unit tests
 - Added the `SolverIntro` which handles inverse-dynamics OC problems + unit tests
 - Added invdyn examples and log files + cleaned up filenames
 - Enabled copyable for various objects used in Python 
 - Supported different contact/impulse frames + unit test + changes in example/logfiles.
 - Removed deprecated FrameXX code.
 - Updated readme file.

Yours,
Carlos

### CODE REVIEW

**Comment by nim65s** [comment]
I think we should include topic/numpy-1.23-compatibility here, and take the opportunity of this major version bump to:
- drop python 2 support
- drop ubuntu 18.04 & python 3.7 support (ref. [discussion in pinocchio](https://github.com/stack-of-tasks/pinocchio/discussions/1931)
- update the tooling to reflect those changes: clang-format v16, black, ruff

Should I go ahead with those tasks, or are there any issues to discuss first ?

On another topic, did somebody test this branch with pinocchio 3x ? If we can avoid the need to make another major crocoddyl version just after the next pinocchio major version, it would be easier.

**Comment by cmastalli** [comment]
You can go ahead, but I think Python stuff are already in this PR.

I haven't tested Pinocchio v3 as don't have access.

**Review by jcarpent — APPROVED** [review]

**Comment by cmastalli** [comment]
@nim65s I noticed you remove some openMP flags that were needed to compile M1 platforms.

I haven't have time to test your commits as I have been in holidays.

Are you sure theses changes works on OSX M1 PCs?

**Comment by wxmerkt** [comment]
I added the libomp-dev for the multi-threading CI and it builds and most tests run. Three are failing:
```
   	 51 - example-python-humanoid_manipulation (Child aborted)
  	 52 - example-python-humanoid_manipulation_ubound (Child aborted)
  	 53 - example-python-humanoid_taichi (Child aborted)
```

Do you think this is due to a missing package?

**Comment by cmastalli** [comment]
> I added the libomp-dev for the multi-threading CI and it builds and most tests run. Three are failing:
> 
> ```
>    	 51 - example-python-humanoid_manipulation (Child aborted)
>   	 52 - example-python-humanoid_manipulation_ubound (Child aborted)
>   	 53 - example-python-humanoid_taichi (Child aborted)
> ```
> 
> Do you think this is due to a missing package?

Could you share more details to debug these failures?

**Comment by cmastalli** [comment]
@nim65s and @wxmerkt -- I have reverted commit f77e1db440cbaf16d90561bea83f088d3b0aadd1, as I don't like the way is handled inside cmake submodule. I really like to push "enter" and move from different options. If we propagate this good practice to the submodule, then I am happy to rely on it.

Additionally, that commit was compiling the code in Debug mode. You can see that examples were taking minutes to solve. This might be also related to the reported failure by @wxmerkt.

**Comment by cmastalli** [comment]
> @nim65s I noticed you remove some openMP flags that were needed to compile M1 platforms.
> 
> I haven't have time to test your commits as I have been in holidays.
> 
> Are you sure theses changes works on OSX M1 PCs?

I have tested this on my M1 MacBook. It works! (fyi @nim65s)

**Comment by nim65s** [comment]
> I don't like the way is handled inside cmake submodule.

What are you talking about exactly ? The code really looks the same to me:
https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/base.cmake#L395-L405

**Comment by cmastalli** [comment]
> > I don't like the way is handled inside cmake submodule.
> 
> 
> 
> What are you talking about exactly ? The code really looks the same to me:
> 
> https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/base.cmake#L395-L405

I didn't review the code, but I checked it in my PC and was not working as expected. Not sure what it is happening but you can see that the jobs are passing now. Therefore, it seems this issue was happening in the server as well.

If you sorted out this issue, we could definitely inject your commit back.

**Comment by nim65s** [comment]
I checked on mine, and it works as expected. I suspect you forgot to update your submodule. Could you double-check that ?

**Comment by cmastalli** [comment]
> I checked on mine, and it works as expected. I suspect you forgot to update your submodule. Could you double-check that ?

I just double-checked it and confirmed that cmake submodule was updated. Are you sure you checkout to 
adb2c14632ea41df7db29d8eaed65751c9dded1c?

Otherwise, it is weird why works for you. I am testing this with my M1 MacBook using Clang. Again, note that this issue was occurring in the ROS jobs. Here, you can see the computation time needed to solve each problem: https://github.com/loco-3d/crocoddyl/actions/runs/4797756967/jobs/8535140841#step:4:2202. And I know these numbers occur when we compile in Debug mode.

**Comment by cmastalli** [comment]
> > I checked on mine, and it works as expected. I suspect you forgot to update your submodule. Could you double-check that ?
> 
> I just double-checked it and confirmed that cmake submodule was updated. Are you sure you checkout to [adb2c14](https://github.com/loco-3d/crocoddyl/commit/adb2c14632ea41df7db29d8eaed65751c9dded1c)?
> 
> Otherwise, it is weird why works for you. I am testing this with my M1 MacBook using Clang. Again, note that this issue was occurring in the ROS jobs. Here, you can see the computation time needed to solve each problem: https://github.com/loco-3d/crocoddyl/actions/runs/4797756967/jobs/8535140841#step:4:2202. And I know these numbers occur when we compile in Debug mode.

I als

**Comment by cmastalli** [comment]
@nim65s --I believe we can proceed with this PR. Perhaps, we can later address the cmake issue.

**Comment by nim65s** [comment]
There are multiple other things blocking me to correctly test this in the various dependencies of the project anyway, so we have time to fix CMake here I think :)

**Comment by nim65s** [comment]
Here is my latest try with this CMake build type:
```Dockerfile
FROM ubuntu:jammy

# Setup Robotpkg apt binary repository
ADD http://robotpkg.openrobots.org/packages/debian/robotpkg.key /
RUN --mount=type=cache,sharing=locked,target=/var/cache/apt \
    --mount=type=cache,sharing=locked,target=/var/lib/apt \
    apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -qqy --no-install-recommends \
    gnupg2 \
 && gpg --dearmor /robotpkg.key \
 && mv /robotpkg.key.gpg /usr/share/keyrings/robotpkg.gpg \
 && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/robotpkg.gpg] \
          http://robotpkg.openrobots.org/packages/debian/pub jammy robotpkg" \
 >> /etc/apt/sources.list.d/robotpkg.list \
 && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/robotpkg.gpg] \
          http://robotpkg.openrobots.org/wip/packages/debian/pub jammy robotpkg" \
 >> /etc/apt/sources.list.d/robotpkg.list

# install crocoddyl dependencies
RUN --mount=type=cache,sharing=locked,target=/var/cache/apt \
    --mount=type=cache,sharing=locked,target=/var/lib/apt \
    apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -qqy --no-install-recommends \
    ca-certificates \
    cmake \
    git \
    make \
    robotpkg-py310-crocoddyl \
 && apt-get remove -qqy \
    robotpkg-py310-crocoddyl

# Get crocoddyl
RUN git clone --recursive -j4 -b release/v2.0.0 https://github.com/loco-3d/crocoddyl

ENV CMAKE_PREFIX_PATH=/opt/openrobots
ENV CMAKE_BUILD_TYPE=Debug

CMD cmake -B build -S crocoddyl \
 && grep CMAKE_BUILD_TYPE build/CMakeCache.txt
 ```
 
 correctly prints 
 ```
 […]
  -- Build files have been written to: /build
 CMAKE_BUILD_TYPE:STRING=Debug
 ```
 
 and if I remove `ENV CMAKE_BUILD_TYPE=Debug` I correctly get
 ```
 -- CMAKE_BUILD_TYPE has automatically been set to Release
 […]
 -- Build files have been written to: /build
CMAKE_BUILD_TYPE:STRING=Release
//STRINGS property for variable: CMAKE_BUILD_TYPE
CMAKE_BUILD_TYPE-STRINGS:INTERNAL=Debug;Release;RelWithDebInfo;MinSizeRel

**Comment by cmastalli** [comment]
> Here is my latest try with this CMake build type:
> 
> ```dockerfile
> FROM ubuntu:jammy
> 
> # Setup Robotpkg apt binary repository
> ADD http://robotpkg.openrobots.org/packages/debian/robotpkg.key /
> RUN --mount=type=cache,sharing=locked,target=/var/cache/apt \
>     --mount=type=cache,sharing=locked,target=/var/lib/apt \
>     apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -qqy --no-install-recommends \
>     gnupg2 \
>  && gpg --dearmor /robotpkg.key \
>  && mv /robotpkg.key.gpg /usr/share/keyrings/robotpkg.gpg \
>  && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/robotpkg.gpg] \
>           http://robotpkg.openrobots.org/packages/debian/pub jammy robotpkg" \
>  >> /etc/apt/sources.list.d/robotpkg.list \
>  && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/robotpkg.gpg] \
>           http://robotpkg.openrobots.org/wip/packages/debian/pub jammy robotpkg" \
>  >> /etc/apt/sources.list.d/robotpkg.list
> 
> # install crocoddyl dependencies
> RUN --mount=type=cache,sharing=locked,target=/var/cache/apt \
>     --mount=type=cache,sharing=locked,target=/var/lib/apt \
>     apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -qqy --no-install-recommends \
>     ca-certificates \
>     cmake \
>     git \
>     make \
>     robotpkg-py310-crocoddyl \
>  && apt-get remove -qqy \
>     robotpkg-py310-crocoddyl
> 
> # Get crocoddyl
> RUN git clone --recursive -j4 -b release/v2.0.0 https://github.com/loco-3d/crocoddyl
> 
> ENV CMAKE_PREFIX_PATH=/opt/openrobots
> ENV CMAKE_BUILD_TYPE=Debug
> 
> CMD cmake -B build -S crocoddyl \
>  && grep CMAKE_BUILD_TYPE build/CMakeCache.txt
> ```
> 
> correctly prints
> 
> ```
> […]
>  -- Build files have been written to: /build
> CMAKE_BUILD_TYPE:STRING=Debug
> ```
> 
> and if I remove `ENV CMAKE_BUILD_TYPE=Debug` I correctly get
> 
> ```
> -- CMAKE_BUILD_TYPE has automatically been set to Release
> […]
> -- Build files have been written to: /build
> CMAKE_BUILD_TYPE:STRING=Release
> //STRINGS property for variable: CMAKE_BUILD_TYPE
> CMAKE_BUILD_TYPE-STRINGS:INTERNAL=Debug;Release;RelWithDebInfo;MinSizeRel
> ```


It works well from my side as well. I am happy to proceed if there is nothing else you wish to improve.

**Comment by nim65s** [comment]
(for the latest commit, ref https://github.com/numpy/numpy/pull/21403)

**Pull request merged**
