### PR TITLE
[multicopter] added brief model explanation

### PR DESCRIPTION
**Pull request by PepMS**
In #736 , @wxmerkt ask for a little explanation and references to guide the user when using the MultiCopter actuation model.

The current PR aims to give that explanation.

### CODE REVIEW

**Comment by wxmerkt** [comment]
Thank you! One more thing: In the code there are several unused parameters (e.g. in `calcDiff` when no different needs to be calculated). This throws a lot of warnings. Could you please also address them?

E.g. `calcDiff(const Eigen::VectorXd& /* x */ ...` to stop the warning from being triggered. Thank you :-)

**Comment by PepMS** [comment]
Done (sorry for the two commits and their respective push, I forgot to format)

**Comment by wxmerkt** [comment]
Thank you :-)

**Comment by cmastalli** [comment]
Thank @PepMS for moving this forward.
Thank @wxmerkt for reviewing this code.

**Pull request merged**
