### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by traversaro**

### CODE REVIEW

**Comment by hrp2-14** [comment]
Hi ! This project doesn't usually accept pull requests on master. If this wasn't intentionnal, you can change the base branch of this pull request to devel (No need to close it for that). Best, a bot.

**Comment by traversaro** [comment]
> 
> 
> Hi ! This project doesn't usually accept pull requests on master. If this wasn't intentionnal, you can change the base branch of this pull request to devel (No need to close it for that). Best, a bot.

Hi @hrp2-14 ! I actually check for any policy like that in https://github.com/loco-3d/crocoddyl/blob/master/CONTRIBUTING.md, but I could not find any indication to which branch a PR should be opened against, perhaps it could make sense to add a link explaining that, thanks! Best, a human.

**Review by jcarpent — APPROVED** [review]
Like the answer ;)

**Comment by proyan** [comment]
Thanks Silvio for the fix :)

**Pull request merged**
