### PR TITLE
Fixed computation of coefficient in  poly-two-rk4 parametrization

### PR DESCRIPTION
**Pull request by cmastalli**
Hey @andreadelprete!

I noticed we have an error in the computation of `c[1]`, which it is fixed in this PR.
Additionally, this fixes the numerical-convergence issues on the MPC algorithm which I reported to you.

Thanks for sharing your notes.
I will later (no in this PR) work on RK3 integrator and its parametrization.

### CODE REVIEW

**Comment by hrp2-14** [comment]
Hi ! This project doesn't usually accept pull requests on master. If this wasn't intentionnal, you
can change the base branch of this pull request to devel (No need to close it for that). Best, a bot.

**Comment by andreadelprete** [comment]
Hi @cmastalli , well done! I confirm there was an error. We should probably extend the unit tests so that these errors are catched.

**Comment by cmastalli** [comment]
> Hi @cmastalli , well done! I confirm there was an error. We should probably extend the unit tests so that these errors are catched.

Yes, we should indeed test this. But, to be honest, I don't know how to do it as the error was in the `calc` function.
Note that we are testing `calcDiff` and the Jacobian-multiplication operators:
 - https://github.com/loco-3d/crocoddyl/blob/devel/unittest/test_controls.cpp#L22
 - https://github.com/loco-3d/crocoddyl/blob/devel/unittest/test_controls.cpp#L44
 - https://github.com/loco-3d/crocoddyl/blob/devel/unittest/test_controls.cpp#L71

If you have an idea how to unit-test the `calc` functions, then please let me know.

Btw, I would like to discuss with you again about the control-parametrization API.
At the moment, I don't see the justification of having two operators: one for the Jacobian, another one for its transpose.
Is there something that I am missing?

(Please note that this development has not been deployed in the master branch, so, we could easily adjust the API)

**Comment by andreadelprete** [comment]
Maybe we can test that the parametrization PolyTwoRK4 gives p0 for t=0, p1 for t=0.5 and p2 for t=1.

**Pull request merged**
