### PR TITLE
Release v1.7.0

### PR DESCRIPTION
**Pull request by cmastalli**
Hi @nim65s,

This new release incorporates the following points:
 1. Updated the examples based on new API in example-robot-data
 2. Removed reference in `std::sized_t` (and other primitives)
 3. Improved computation and handled richer conditions in friction and wrench cone (e.g., inner/outer apprx. in wrench cone, and rotation matrix in friction cone)
 4. Added more unit-tests for cones
 5. Included the CoP support notion
 6. Updated minimal version of EigenPy as it fixes a bug with 4x6 matrices
 7. Developed a gravity-based cost function for both free and in contact conditions (included its unit-test code)
 8. Added assignment operator in FrameXXX structures
 9. Replaced `isMuchSmallerThan` by `isZero` in all the unit-tests
 10. Enabled free-flyer joint in full actuation model
 11. Improved multicopter actuation API + unit-tests
 12. Exposed in Python ActionModelUnicyle::dt_
 13. Fixed multithreading support: running the correct number of threads
 14. Enabled that the user can set the number of threads (also in Python)
 15. Added publication list and updated README file
 16. Registered in Python the shared pointers of all the model classes
 17. Fixed Meshcat visualizer after update
 18. Added Github Action CI with ROS dependency resolution
 19. Improved efficiency of backward pass by defining properly RowMajor matrices
 20. Activated all warnings and Werror
 21. Improved documentation

### CODE REVIEW

**Comment by hrp2-14** [comment]
Hi ! This project doesn't usually accept pull requests on master. If this wasn't intentionnal, you can change the base branch of this pull request to devel (No need to close it for that). Best, a bot.

**Comment by wxmerkt** [comment]
Can we wait with the release for another PR? There is also a fix required for exposing the RowMajor vectors which I have as part of the BoxFDDP performance improvement branch that I want to open as a PR maybe tomorrow - otherwise I'll cherry-pick the fix (it needs to be part of the release)

**Comment by proyan** [comment]
@cmastalli We should merge #899 as well before making a release. If you don't have any further comments or commits to make, I would go ahead with the merge.

This would make this release heavy enough to merit a minor version bump.

**Comment by cmastalli** [comment]
@wxmerkt yes, let's wait o merge that PR.

@proyan we could do it, but I was thinking to create another release after that (since it is a bit PR, and I would prefer to keep it in the devel branch for at least couple of weeks, thus we have time  to use it). Let me know if you agree, otherwise I am happy to wait as well ;)

**Comment by proyan** [comment]
OK, let's make sure the residual models are beta tested first

**Comment by cmastalli** [comment]
I have included #943 in this release.

@nim65s -- as agreed with @proyan, you could proceed with this release.

**Comment by proyan** [comment]
@nim65s ping:)
Could we please make this release?

**Comment by nim65s** [comment]
I thought it was already done, but it looks that my push failed… Thanks for the ping :)

**Pull request merged**
