### PR TITLE
Hotfix for exposing std::vector<MatrixXdRowMajor>

### PR DESCRIPTION
**Pull request by wxmerkt**
Required before #942

### CODE REVIEW

**Comment by proyan** [comment]
It would be good if we try to keep close to pinocchio nomenclature. Could you please rename the RowMajor Matrix to `RowMatrixXs`?

https://github.com/stack-of-tasks/pinocchio/blob/master/src/multibody/data.hpp#L77

**Comment by wxmerkt** [comment]
Thank you for the pointer @proyan. I've fixed it for the binding here and will amend in the next PR I'll open with more RowMajor changes.

**Review by proyan — APPROVED** [review]
Thanks for the PR @wxmerkt

**Review by cmastalli — APPROVED** [review]
Thanks @wxmerkt and @proyan.
Let's merge this PR before the residual one :)

**Pull request merged**
