### PR TITLE
Created a to_string function for c++98 compatibility

### PR DESCRIPTION
**Pull request by cmastalli**
I know we have discussed about to stick only with c++11 and higher. This solution can be quickly adapted if we decided to move forward.

### CODE REVIEW

**Comment by wxmerkt** [comment]
Can we put this into the `std` namespace if the C++ version is less than 2011 to avoid having to change so many files when we do make the switch to C+11?

**Comment by cmastalli** [comment]
> switch

done! I am waiting for the results on the gepgitlab CI. In github, we don't have 16.04 jobs; so I can't fully check it here. Should we include them in Github?

**Comment by wxmerkt** [comment]
We can include 16.04 in Travis, but it may slow down the CI quite a bit (each additional build ~30min)

**Comment by cmastalli** [comment]
> We can include 16.04 in Travis, but it may slow down the CI quite a bit (each additional build ~30min)

I see
@nim65s do you have any suggestion?

**Comment by nim65s** [comment]
I'll suggest to keep travis configuration as minimal as possible. It should be able to show quickly simple issues, while we can use gitlab CI for long and exhaustive builds.
My point is I'll spend a lot of time on tuning gitlab CI anyway, so it would be better to avoid spending too much time in travis configuration and maintainance in individual projects.

**Comment by cmastalli** [comment]
> I'll suggest to keep travis configuration as minimal as possible. It should be able to show quickly simple issues, while we can use gitlab CI for long and exhaustive builds.
> My point is I'll spend a lot of time on tuning gitlab CI for all projects at once anyway, so it would be better to avoid spending too much time in travis configuration and maintenance in individual projects.

For your the minimalist version of Travis only includes 18.04, don't you?

**Comment by wxmerkt** [comment]
The Travis has already been set up for 16.04 and 18.04 now. We can take 16.04 out again if desired.

**Comment by nim65s** [comment]
if including more than one distribution is strictly adding one more line with the distribution name, and that it doesn't require way more time to run, we can keep it. If this require any additionnal work, we shouldn't, IMO.

**Pull request merged**
