### PR TITLE
Release v1.6.0

### PR DESCRIPTION
**Pull request by cmastalli**
Hi @nim65s,

It has been a while that we do not release Crocoddyl.
This new version incorporates the following points:
  1. Refactored the Cost API with breaking compatibility (cost depends on state abstract, not multibody state)
  2. Fixed issue in c++98 compatibility
  3. Added shared_ptr registers for solver classes (Python bindings)
  4. Initialized missed data in SolverQP (not really producing a bug)
  5. Fixed issue with FrameXXX allocators (Python bindings)
  6. Created aligned std vectors for FrameXXX (Python bindings)
  7. Used the proper `nu`-dimension in shooting problem and solvers
  8. Doxygen documentation of smooth-abs activation
  9. Renamed the activation model: smooth-abs to smooth-1norm (deprecated old names)
  10. Added the smooth-2norm activation model with Python bindings
  11. Updated README file with Credits and committee information
  12. Added throw_pretty in Python bindings of action models (checks x,u dimensions)
  13. Improved the documentation (doxygen, docstrings), and fixed grammar, of various classes
  14. Cleaned up a few things related with cost classes
  15. Cleaned up unnecessary typedef in cost models
  16. Extended the differential action model for contacts to handle any actuation model (not just floating-base derived ones)
  17. Added conda support
  18. Added the quadratic-flat activation models
  19. Fixed issue with gepetto viewer display (appearing in some OS)
  20. Added contact/impulse action unit tests
  21. Added contact/impulse cost unit tests
  22. Added a proper gap threshold (it was too big and created different behavior in feasibility-driven solvers)
  23. Improved the copyright starting year for many files

I have pushed this branch to my current fork, feel free to push the needed commits before the release.

### CODE REVIEW

**Comment by hrp2-14** [comment]
Hi ! This project doesn't usually accept pull requests on master. If this wasn't intentionnal, you can change the base branch of this pull request to devel (No need to close it for that). Best, a bot.

**Comment by cmastalli** [comment]
@nim65s should we include the online documentation in the README file (i.e., https://gepettoweb.laas.fr/doc/loco-3d/crocoddyl/master/doxygen-html/)?

Note that I did not complete the documentation of each class; however, there is a reasonable number of documented classes.

**Comment by proyan** [comment]
Yes! :)
It would definitely be helpful and we have enough content to get started

**Comment by cmastalli** [comment]
@proyan and @nim65s  --  I have included the documentation in the README file (aed7a81).

For my side, @nim65s -- you could go ahead with this release :)

**Comment by nim65s** [comment]
Done, sorry for the delay :/

**Comment by cmastalli** [comment]
Thanks @nim65s :)

**Pull request merged**
