### PR TITLE
Understanding the relinearization in differental manifolds (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by cmastalli**
This PR intends to open a discussion regarding the relinearization perform in the DDP backward pass.
As discussed with @nmansard and @jcarpent, it seems to me that we need to apply a parallel transport of the `Vxx` during the backward relinearization (https://github.com/loco-3d/crocoddyl/blob/devel/src/core/solvers/ddp.cpp#L182). Concretely speaking, I suspect that `Vxx_next` lies in a different tangent space to `Vx`.

@nmansard I commented the lines that are not passing. You could run it in your PC like this:
```cpp
cp ${crocoddyl_path}/unittest/python/
python test_solvers.py
```

Note that this is legacy code which we never modified.

### CODE REVIEW

**Comment by cmastalli** [comment]
@jmirabel you might want to give your feedback.

**Comment by jmirabel** [comment]
@cmastalli is it really my review you asked for ? I believe you made a mistake. If no, I need a bit of context.

**Comment by cmastalli** [comment]
> @cmastalli is it really my review you asked for ? I believe you made a mistake. If no, I need a bit of context.

@jmirabel I want to confirm with you that the parallel transport in Lie algebra has the form:



where   transport a tangent vector  to the tangent space ,  is the configuration manifold, and  is the operator Jacobian computed using Pinocchio.

**Comment by jcarpent** [comment]
This Jint that as to be used here.
More precisely, using Pinocchio's convention and code, what you're looking for:
```
Jint = dIntegrate(model,q1,difference(model,q1,q2),ARG0)
```
This operator transports the tangent space of T_q2 to the tangent space of T_q1.

**Comment by jmirabel** [comment]
What is the operation you differentiate ?

**Comment by cmastalli** [comment]
> This Jint that as to be used here.
> More precisely, using Pinocchio's convention and code, what you're looking for:
> 
> ```
> Jint = dIntegrate(model,q1,difference(model,q1,q2),ARG0)
> ```
> 
> This operator transports the tangent space of T_q2 to the tangent space of T_q1.

Indeed, my notation is equivalent to this Pinocchio code. When I wrote it, I used the Crocoddyl notation.



> What is the operation you differentiate ?
It's is the diff operator. @jcarpent wrote a code that retrieve that one from the Jacobian of the integrator.

**Comment by jcarpent** [comment]
Jdiff is equivalent to dDifference ;)

**Comment by jcarpent** [comment]
@cmastalli, you have to use the dIntegrate instead, giving:
`v_1 = Jint * v2`

**Comment by proyan** [comment]
@cmastalli Could I close this PR?

**Comment by cmastalli** [comment]
> @cmastalli Could I close this PR?

No, don't do it. I need to finish this work.

**Comment by proyan** [comment]
Since there hasn't been any activity at all on this PR for almost a month and a half, could you instead open another PR when it is ready?

**Comment by proyan** [comment]
@cmastalli 
Could you please close this PR? I think that it has served its purpose.

**Comment by cmastalli** [comment]
>  Could you please close this PR? I think that it has served its purpose.

Let's close it because I don't have time.
@proyan note that we still need to investigate if it is needed to apply the parallel transport in the backward pass.

**Pull request closed without merging**
